#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rinutils
Version  : 0.2.0
Release  : 1
URL      : https://github.com/shlomif/rinutils/releases/download/0.2.0/rinutils-0.2.0.tar.xz
Source0  : https://github.com/shlomif/rinutils/releases/download/0.2.0/rinutils-0.2.0.tar.xz
Summary  : Shlomi Fish's gnu11 C Library of Random headers
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(cmocka)

%description
Shlomi Fish's gnu11 C Library of Random headers.

%package dev
Summary: dev components for the rinutils package.
Group: Development
Provides: rinutils-devel = %{version}-%{release}
Requires: rinutils = %{version}-%{release}

%description dev
dev components for the rinutils package.


%prep
%setup -q -n rinutils-0.2.0
cd %{_builddir}/rinutils-0.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581553952
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1581553952
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/Rinutils/cmake/RinutilsConfig.cmake
/usr/lib64/Rinutils/cmake/RinutilsConfigVersion.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/rinutils/alloc_wrap.h
/usr/include/rinutils/bit_rw.h
/usr/include/rinutils/count.h
/usr/include/rinutils/dllexport.h
/usr/include/rinutils/exit_error.h
/usr/include/rinutils/likely.h
/usr/include/rinutils/longlong.h
/usr/include/rinutils/min_and_max.h
/usr/include/rinutils/portable_time.h
/usr/include/rinutils/rin_cmocka.h
/usr/include/rinutils/rinutils.h
/usr/include/rinutils/str_utils.h
/usr/include/rinutils/typeof_wrap.h
/usr/include/rinutils/unused.h
/usr/lib64/pkgconfig/librinutils.pc
