#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : rinutils
Version  : 0.10.2
Release  : 4
URL      : https://github.com/shlomif/rinutils/releases/download/0.10.2/rinutils-0.10.2.tar.xz
Source0  : https://github.com/shlomif/rinutils/releases/download/0.10.2/rinutils-0.10.2.tar.xz
Summary  : Shlomi Fish's gnu11 C Library of Random headers
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(cmocka)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Shlomi Fish's gnu11 C Library of Random headers.

%package dev
Summary: dev components for the rinutils package.
Group: Development
Provides: rinutils-devel = %{version}-%{release}
Requires: rinutils = %{version}-%{release}

%description dev
dev components for the rinutils package.


%prep
%setup -q -n rinutils-0.10.2
cd %{_builddir}/rinutils-0.10.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1694735053
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export CFLAGS="$CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1694735053
rm -rf %{buildroot}
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/rinutils/alloc_wrap.h
/usr/include/rinutils/bit_rw.h
/usr/include/rinutils/count.h
/usr/include/rinutils/dllexport.h
/usr/include/rinutils/exit_error.h
/usr/include/rinutils/likely.h
/usr/include/rinutils/longlong.h
/usr/include/rinutils/min_and_max.h
/usr/include/rinutils/portable_time.h
/usr/include/rinutils/rin_cmocka.h
/usr/include/rinutils/rinutils.h
/usr/include/rinutils/str_utils.h
/usr/include/rinutils/typeof_wrap.h
/usr/include/rinutils/unused.h
/usr/lib64/cmake/Rinutils/RinutilsConfig.cmake
/usr/lib64/cmake/Rinutils/RinutilsConfigVersion.cmake
/usr/lib64/pkgconfig/librinutils.pc
